[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@openzeppelin/=lib/openzeppelin-contracts']
ETH_RPC_URL = 'https://rinkeby.infura.io/v3/b9b510f5a820476095491a68bcecd07e'
# See more config options https://github.com/gakonst/foundry/tree/master/config